### ISSUE TITLE
Discard items doesn't work

### ISSUE THREAD

**Issue by dyounger** [klavinslab/aquarium-bugs#104]
The discard items plan doesn't work. It is also very clunky as it is now. I would like to be able to have a choice of either selecting specific item numbers OR giving an object ID and then selecting whatever items I want to get rid of for that object. It should also be possible to easily delete multiple items in a single plan.

**Comment by klavins** [comment]
I wonder if the sample should be the input to this protocol so then the user would choose which item when they fill in the sample name?

**Comment by klavins** [comment]
Might also be an array input top the user only has to submit one plan.

**Comment by ayeshasal** [comment]
i think we can do array inputs for this -- that way, you can delete specific items for a single object type by inputting all the sample ids of that object type you wanna get rid of.

**Comment by gasnew** [comment]
Justin's Discard List of Items should address all this! I've updated it to include an optional array input as well.
