### ISSUE TITLE
How to find history of an item?

### ISSUE THREAD

**Issue by dyounger** [klavinslab/aquarium-bugs#106]
I can't figure out how to see the history of an item. If I click on an item in the inventory, it just gives the data associated with that item. I should be able to go back and very clearly see all of the times that item has been touched and all of the plans that were run in order to make that item.

**Comment by klavins** [comment]
One idea is to put the old into info from Aq1 in the new item popup.

**Comment by klavins** [comment]
The history of an item is now shown in the item popup.
