### ISSUE TITLE
Collection inputs remain "orange" if selected on first row

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#108]
If the first row of a collection input is select inputs will be unsatisfied. Transformation can be used as a minrep:

Second Row Selected:
<img width="395" alt="screen shot 2017-08-07 at 8 06 36 pm" src="https://user-images.githubusercontent.com/10437900/29054595-f0d699de-7bab-11e7-951f-b3d5f5568420.png">

First Row Selected:
<img width="395" alt="screen shot 2017-08-07 at 8 06 31 pm" src="https://user-images.githubusercontent.com/10437900/29054596-f0d817d2-7bab-11e7-9285-b8466b20bfe0.png">

**Comment by klavins** [comment]
Fixed
