### ISSUE TITLE
Collection not showing up in browser and planner properly

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#11]
This is an issue with both Aq1 and Aq2. Collections are not appearing in the Aq1 and Aq2 browser (or Aq2 Planner) but will show up in the ../samples/sample_id page.

As an example:
- Stripwell collections show up here: http://54.68.9.194:81/samples/20321
- However, in the sample browser, the stripwells will not appear

This is an issue since we cannot submit some operations that use collections as inputs.

**Comment by klavins** [comment]
I think I fixed this. Check out http://52.27.43.242/browser?sid=20321 and also try planning with it.
