### ISSUE TITLE
Graphical Planner: Operations with on the fly predecessors get stuck in waiting

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#112]
If an operation has an on-the-fly predecessor, it gets stuck in waiting, whereas it should be in pending since its pred is on-the-fly

**Comment by jvrana** [comment]
MinRep (located in MinRep category):

<img width="188" alt="screen shot 2017-08-08 at 9 03 58 am" src="https://user-images.githubusercontent.com/10437900/29081833-8f076f90-7c18-11e7-8800-c6b10c8bfea3.png">

**Comment by klavins** [comment]
Ok, I believe I fixed this. Now, if an op has only on the fly predecessors then it wills start in pending mode instead of waiting mode.
