### ISSUE TITLE
Graphical Planner: Long operation name displays incorrectly

### ISSUE THREAD

**Issue by Gamemackerel** [klavinslab/aquarium-bugs#116]
In order to display operations names on one line, it looks like you want any name that is too long for displaying on one line to be cut short and appended with ellipsis.
It's a little hard to see what's happening in the image but for my browser the "make Electrocompetent Cells (JV Optimized)" operation name is handled wrong - for some reason the ellipsis wants its own line.

![capture](https://user-images.githubusercontent.com/3107677/29090580-d9fd6998-7c34-11e7-9ce6-a183dd74b77d.PNG)

Chrome Version 60.0.3112.90 Windows 10

**Comment by Gamemackerel** [comment]
Trimming 3 more chars should do the trick
![capture](https://user-images.githubusercontent.com/3107677/29093502-e794e464-7c3e-11e7-9327-9c072a1c51bd.PNG)

**Comment by klavins** [comment]
Its because your browser is adding that scrollbar. I've had these scrollbar issues before and I think I know how to fix them.
