### ISSUE TITLE
Lyophilized primer items not being deleted after rehydration

### ISSUE THREAD

**Issue by dyounger** [klavinslab/aquarium-bugs#118]
It seems as though the lyophilized primer items are not being deleted when a primer stock is made. 

Ideally, the lyophilized primer would "turn into" a primer stock and not get a new item ID (similar to an unverified plasmid stock turing into a plasmid stock). That way, one unique ID number can be written on the tube and that number will still be valid after rehydration.

**Comment by gasnew** [comment]
Fixed! Lyophilized primers will now just be transient items that are deleted after Rehydrate Primer finishes.
