### ISSUE TITLE
Users are being incorrectly charged for glycerol stocks.

### ISSUE THREAD

**Issue by cpc3** [klavinslab/aquarium-bugs#122]
If a user says their sequencing is incorrect, the plate and stock are thrown out, but they are still being charged for a glycerol stock even though one isn't made.

**Comment by Gamemackerel** [comment]
Not sure how the cost service works, so I hesitate to make any changes. 
Can this be fixed simply by making this addition to the each loop in "Discard plasmid stocks for no" block?


<pre>  
    show do
        title "Discard Plasmid Stocks from bad sequencing results"
        
        note "Please discard the following Plasmid Stocks:"
        operations.select { |op| op.temporary[:no] }.each do |op|
            stock = op.input("Plasmid").item
            note "Plasmid Stock #{stock.id} at #{stock.location}"
            stock.mark_as_deleted
            stock.save
            <b>op.error :bad_seq, "Bad sequencing results."</b>
        end
    end if operations.any? { |op| op.temporary[:no] }
</pre>

**Comment by ayeshasal** [comment]
yeah, i think that should fix it! nice. i'll check to make sure but i'm closing this issue for now
