### ISSUE TITLE
One operation input can take more than one wire

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#127]
This sort of topology should not be possible. When I launch and run the plan, only one of the StS outputs is used as the input to USR.
![badplan](https://user-images.githubusercontent.com/14169359/29201105-32c250a2-7e10-11e7-84c8-e2c27ad24b30.png)

**Comment by ayeshasal** [comment]
this and #139 are pretty much the same issue, except 139 deals w output --> multiple inputs and this deals w multiple output --> input. i'm going to close this issue and then add a comment on #139.
