### ISSUE TITLE
Templates "add" rather than "replace"

### ISSUE THREAD

**Issue by dyounger** [klavinslab/aquarium-bugs#135]
When you click on a template, it adds all of the tasks from that template rather than starting fresh from a blank plan that just has the template. 

Ex. if I click on a template twice, it adds two identical copies of the saved template directly on top of one another. The only way I could tell this was going on was because the estimated cost was double what I would have expected, but this is probably not something that everyone will check. You also only end up editing the top template, so this will likely cause a lot of confusion.

**Comment by Gamemackerel** [comment]
Closing because #207 was fixed, and templates being added rather than starting a fresh plan isn't necessarily a bad thing if the template stacking issue is gone.
