### ISSUE TITLE
Graphical planner allows more than one wire from an output to an input

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#139]
You can add two overlapping wires in the graphical planner. In the example below, a user should not be allowed to create another wire from Packaging Plate output to the Harvest Lentivirus input since this wire already exists. Currently you can create another overlapping wire by shift-click; you can tell there is more than one wires by selecting and deleting the 'top' wire, while the wires below remain.

<img width="330" alt="screen shot 2017-08-15 at 12 32 19 pm" src="https://user-images.githubusercontent.com/10437900/29332841-4d369b60-81b6-11e7-8934-e3face3d3145.png">

**Comment by bjkeller** [comment]
Rephrasing: if a wire exists from an output to an input, then a new one should not be added.

**Comment by ayeshasal** [comment]
#127 was about a similar issue, except in that case the issue was that there were multiple outputs being wired into one input, which should not have been allowed.
