### ISSUE TITLE
As a researcher, I want to be able to select multiple/all preferred predecessor of an operation with multiple object_type options

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#14]
I'm having trouble with selecting multiple preferred predecessors for operations with multiple object_type options. Particularly with the Make PCR Fragment operation, which can take in either Plasmid Stock, Unverified Plasmid Stock, 1ng/ul Plasmid Stock, 1ng/ul Fragment Stock. I thought usually, each one of these could have its own preferred predecessor (based on what you select in the Planner and clicking "Auto"). I've used this feature before and its super useful.

However I can't seem to select all of the preferred predecessors for Make PCR Fragment. Some check boxes will disappear when you click other boxes. Once you finally get all your boxes checked, if you look back in the developer, only one box is checked.

**Comment by ayeshasal** [comment]
this is no longer relevant since we got rid of the "auto" button
