### ISSUE TITLE
Upload Sequencing doesn't appear to work correctly

### ISSUE THREAD

**Issue by cpc3** [klavinslab/aquarium-bugs#144]
It appears upload sequencing doesn't upload the correct results to plans.  And if one plan should have multiple results only one is being uploaded. 

![dy_seq](https://user-images.githubusercontent.com/20099015/29420281-5fc870d4-8326-11e7-8297-fbbdb3dab19c.PNG)

![seq_2](https://user-images.githubusercontent.com/20099015/29420243-485c1afe-8326-11e7-9d44-b8e4a0c47d63.PNG)

**Comment by gasnew** [comment]
This should be fixed now! Reopen if it crops up again. :)
