### ISSUE TITLE
Stripwells not deleted after colony PCR/fragment analyzing

### ISSUE THREAD

**Issue by cpc3** [klavinslab/aquarium-bugs#145]
The stripwells aren't being deleted allowing people to submit jobs with them even though they no longer exist.  For example in Orlando's plan 1872 he is using an old stripwell from a previous colony PCR (meaning he is skipping the lysate step), but this stripwell doesn't exist.

**Comment by gasnew** [comment]
I checked through Run Gel, Colony PCR, and Fragment Analyzing, and all of the stripwells are being deleted in those now on production. Marking as closed now, but please open again if this recurs!
