### ISSUE TITLE
Planner allows you to launch a replanned plan without first saving it

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#155]
This results in cases where the operations in the replanned plan (created from clicking Replan on an old plan) will use items from the old plan's inputs. Saving is necessary for I/O validation. I ran into this in a plan that looked like this
![replano](https://user-images.githubusercontent.com/14169359/29586363-50264d14-873f-11e7-959e-8203c19b9729.png)
where Upload Sequencing Results used, as its input item, the item from an older iteration of this plan, not the item created by Send to Sequencing.

The solution is to require that the new plan is saved before it is launched, I believe.

**Comment by Gamemackerel** [comment]
Fixed in new planner
