### ISSUE TITLE
Can launch plan with bad sample names in field values

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#164]
A user submitted a plan after populating all of his/her inputs and outputs with the item ids they wanted to use instead of the sample ids. When an entered sample id doesn't match an existing sample in the planner, upon saving the plan, you can then select any existing item of the sample type for that field (e.g., [this plan](http://52.27.43.242:81/launcher?plan_id=36641)).

Before saving
![itemidbad](https://user-images.githubusercontent.com/14169359/29730646-ddca3cfe-8995-11e7-83d7-d417e9d5ce7e.png)

After saving
![itemidbad2](https://user-images.githubusercontent.com/14169359/29730649-e1e71fdc-8995-11e7-9f08-7f4e3190ba37.png)

**Comment by klavins** [comment]
Ok, I fixed this. It isn't elegant, but if the user saves a plan with nonsense in one of the inputs or outputs, then the nonsense disappears after saving, and the io port turns orange. Better would be to explain what happened -- but for now this will prevent this error.
