### ISSUE TITLE
Unable to attach labels to bugs

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#18]
This isn't a bug with Aquarium, but I don't believe the rest of us can attach label to our bugs.

**Comment by dvnstrcklnd** [comment]
Me too? I think maybe we have to be made contribtutors? https://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner

**Comment by gasnew** [comment]
I've added the two of you and @ayeshasal as contributors. Let me know if you can't add labels now!

**Comment by jvrana** [comment]
Thank you it works for me!

**Comment by gasnew** [comment]
Rad!

**Comment by dvnstrcklnd** [comment]
Rad?! Are you sure you don't know what a floppy disk is...

**Comment by gasnew** [comment]
...
