### ISSUE TITLE
As a researcher, I cannot wire Rehydrate Primer to both PCR and to Sequencing

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#186]
[This plan](http://52.27.43.242:81/launcher?plan_id=43547) is a small recreation of this error. When [the PCR job](http://52.27.43.242:81/krill/log?job=64754) is run, it aborts because there is no primer aliquot item associated with one of the operation inputs. We've had to rebuild three of Alberto's plans to work around this.

![cant](https://user-images.githubusercontent.com/14169359/30138031-12737f68-931b-11e7-9a4b-0daa3b0a59ad.png)

**Comment by Gamemackerel** [comment]
I am closing this because it seems to be fixed on the new planner. When you get a chance Garrett, please confirm.
