### ISSUE TITLE
Warn before navigating away in developer

### ISSUE THREAD

**Issue by dvnstrcklnd** [klavinslab/aquarium-bugs#192]
As a workflow developer, I sometimes lose significant amounts of work because I navigate away without saving. It would be nice if the browser would warn me before this happens when in the developer view. 

I believe this would do it:
https://stackoverflow.com/questions/1119289/how-to-show-the-are-you-sure-you-want-to-navigate-away-from-this-page-when-ch

**Comment by bjkeller** [comment]
I made an umbrella issue for editor issues linked to this issue: #193, and am marking this as closed.
