### ISSUE TITLE
minor Planner UI Glitch: wires turning orange when they shoudn't for array inputs

### ISSUE THREAD

**Issue by Gamemackerel** [klavinslab/aquarium-bugs#206]
For wires to array inputs that have correct object/sample type match, they turn orange until filled in with a sample.
![orangewires](https://user-images.githubusercontent.com/3107677/30393680-beb9dcfe-9875-11e7-87b4-e0f7f0797d4f.PNG)

**Comment by Gamemackerel** [comment]
Sam was experiencing other glitches with orange wires for array inputs. I believe for him sometimes wires would be orange even when the output of Purify Gel Slice was connected to an input for Assemble Plasmid and both were green and filled in.  I could not reproduce his issue.

**Comment by klavins** [comment]
Ok, I've updated how this is computed and hopefully it will make sense. Basically, now the object/sample have to match and the samples chosen (if present) has to match. If one or both i/o pins don't have samples, then the wire is not turned orange.
