### ISSUE TITLE
Planner GUI 1844 is not functional

### ISSUE THREAD

**Issue by Gamemackerel** [klavinslab/aquarium-bugs#214]
Plans cannot be launched, and saving seems to only work occasionally.

Outputs and Inputs cannot be selected for operations, as soon as they are typed in, the nodes turn green for a second in confirmation before the field clears itself.

**Comment by klavins** [comment]
Hopefully I fixed this. It uncovered another propagation error, which I also fixed. Please test filling in i/o inputs and outputs and propagation generally.
