### ISSUE TITLE
Items from the outputs of completed operations are not associated with the inputs of successor operations

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#219]
## Bug report

- **Reproduce by:** *Submit a plan with two operations (e.g., Check Plate -> Make Overnight Suspension. [See this plan](http://52.27.43.242:81/launcher?plan_id=47384).). Check Plate appears as expected, but Make Overnight Suspension, after Check Plate is run, exemplifies the bug.*
- **Expected:** *Plate item id should show up in the input row on both Planner and Manager view.*
- **Actual:** *No item id appears.*
- **Acceptance criteria:** *The item id from the previous operation's output should be associated with the succeeding operation's input upon completion of the previous operation.*

**Comment by gasnew** [comment]
It's worth noting that this already works correctly for operations that are leaves in their plans and for operations that have been scheduled, errored, and set back to pending.

**Comment by klavins** [comment]
I have added this functionality. Previously operations.retrieve did this work. Now, when an operation is moved to pending, it looks for predecessor outputs and copies the item and row and column (if any) to the input. 

operations.retrieve still does this too (no harm as far as I can tell).

**Comment by gasnew** [comment]
This is great; thanks!
