### ISSUE TITLE
Plan specific page? (/launcher?plan_id=...)

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#23]
I'm sure this is already on the large TODO list, but when clicking on a plan in the manager (e.g. http://52.27.43.242/launcher?plan_id=44), takes you back to your own plans. If you want to find a specific plan, you have to search for the user on the left and scroll alot to find that plan.

A good feature would be to auto-open that particular plan when you click on it so we can debug folks' plans more efficiently.

**Comment by klavins** [comment]
This one is on my list and will show up soonish.

**Comment by klavins** [comment]
Done!
