### ISSUE TITLE
Sample and item IDs in Manager view

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#24]
It would be helpful for the managers to see sample IDs next to samples and item IDs (where applicable) for operations in the Manager view. Here's where Michelle pointed me:
![thing for thing](https://user-images.githubusercontent.com/14169359/28224758-26fddaa2-6885-11e7-8fff-8d8f33b2c36d.png)

**Comment by klavins** [comment]
Done.
