### ISSUE TITLE
Planner saving issue: updating operation type definition i/o

### ISSUE THREAD

**Issue by Gamemackerel** [klavinslab/aquarium-bugs#242]
- I have a saved plan/template that contains an operation with outputs/inputs

- I edit the operation type definition of that operation to remove an input/output

then when I go back to load the plan, or template:
if it was a plan it gives this popup: "Cannot read property 'routing' of undefined"
if it was a template, the template doesn't load

**Comment by klavins** [comment]
Ah, cool. I'll look at that.

**Comment by Gamemackerel** [comment]
Closing - #242 encompasses what happened here
