### ISSUE TITLE
Nice to add object_types to Data column in job/operation view of the Manager

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#25]
Similar request to #26, which also deals with the Manager view.  

When you click on a job in the Manager page, it displays a nice data table, that is super useful
![screen shot 2017-07-14 at 11 19 41 am](https://user-images.githubusercontent.com/10437900/28225124-6461a86e-6886-11e7-8ef0-d10c4d22f2d5.png)

I think if we also added the object_type from the field value and from the item (if there's an associated item) it'd be faster to debug plans and plan issues, especially with operations that change object types. Something like:

**Data:**
out: Fragment: PS_yeGFP **as a Stripwell**
in: Forward Primer : PS_F_assembly **as a Primer Aliquot** ( 68318 **Primer Aliquot** )
  Reverse Primer : yeGFP-R  **as a Primer Aliquot**  ( 13703 **Primer Aliquot** )
  Template : mScarlet-C **as a Fragment Stock** ( 110602 **Fragment Stock** )

**Comment by jvrana** [comment]
This is also similar to #24

**Comment by klavins** [comment]
Ok, I've added this info, but it looks a bit verbose sometimes:
  Primer Aliquot : 20298: optimization-test-fragment-reverse primer as Primer Aliquot ( 99463 )
