### ISSUE TITLE
Nice to add output item in Data column of the operation/job view of the Manager page

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#26]
Similar request to #25. Output items do not show up in the Data table in the Manager view. Here's a photo of a complete job
![screen shot 2017-07-14 at 11 12 46 am](https://user-images.githubusercontent.com/10437900/28225372-4b54012c-6887-11e7-9526-2f12891e9a73.png)

It would be nice to have the output item that was generated in this data field.

**Comment by gasnew** [comment]
This is also similar to #24

**Comment by klavins** [comment]
Done, I think.
