### ISSUE TITLE
IMPORTANT, Developer. Displayed "Current" version of library module is NOT the current version!

### ISSUE THREAD

**Issue by segoldberg** [klavinslab/aquarium-bugs#262]
## Protocol bug

- **Operation name:** HighThroughputHelper (module), also try pressing "versions" button
- **Expected:** to see most recent version of edited text (from after last "save")
- **Actual:** see something older (from before "save")
- **Link:** http://52.27.43.242:81/operation_types#

**Comment by bjkeller** [comment]
closing because this is the same as #264
