### ISSUE TITLE
Array I/O Glitch on Planner

### ISSUE THREAD

**Issue by Gamemackerel** [klavinslab/aquarium-bugs#268]
## Bug report
When a plan is saved containing an operation with array inputs/outputs, that operation cannot then have its amount of inputs or outputs increased further. The size of the io array is bounded on the top by whatever size it was last saved with.

The size of the array can be decreased just fine.

Reproduce glitch:

- Save plan that has op with 1 array input
- add another input
- Save again

![exampleglitch](https://user-images.githubusercontent.com/3107677/32813349-8dee6c4c-c95e-11e7-8b81-b5548510c03f.gif)

Workaround for users if their input array was initialized too small is to just delete the operation and bring out a fresh one

**Comment by klavins** [comment]
Working on this now. And thank you for the very useful gif.

**Comment by klavins** [comment]
Fixed!
