### ISSUE TITLE
Export of protocol followed by Import adds weird "A-hat" char before "mu"

### ISSUE THREAD

**Issue by segoldberg** [klavinslab/aquarium-bugs#270]
See Parameter Name below:
![image](https://user-images.githubusercontent.com/31996971/32800175-7feb02ac-c92e-11e7-956a-f1e40650681a.png)

## Bug report

Export of protocol (from nursery) followed by Import of .json (into production):
1) adds weird "A-hat" char before "mu" in Definition panel
2) removes all "mu"s from Protocol text 

Reproduce by: 
Export the following protocol from nursery:
Induction - High Throughput/Flow Cytometry 96 well (copy)
Import into production.

**Comment by bjkeller** [comment]
As a workaround, when you want a symbol to be displayed in a protocol use the [html character references](https://dev.w3.org/html5/html-author/charref). In this case, I would use `&micro;` for &micro;L. Since a show is being rendered as HTML this works fine.

**Comment by bjkeller** [comment]
Fixed by https://github.com/klavinslab/aquarium/commit/8fe5aa48cc5644f981a710abd7b785b02f5e0efd
