### ISSUE TITLE
Bug: No longer able to create new Libraries (Nursery)

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#291]
**Reproduce by:** Create a new Library on the developer page. Then update the Library.
**Expected:** The Library is created and you can edit it.
**Actual:** Aquarium immediately deletes the new library and logs you out.
**Acceptance criteria:** You can create, edit and save Libraries in the developer page.

**Comment by klavins** [comment]
I can't reproduce this. It may be that you are not logged in. Aquarium has a bug where you can be logged out but still see the page you were on. But when you try to do something that makes a background json request, it fails because you are not logged in. Could that be it?

**Comment by jvrana** [comment]
I biked home and its working now. I took a look at the json requests it was making and didn't see anything weird. Meanwhile, logging into production, things were working fine. I guess I'm going to close this and the other issue.
