### ISSUE TITLE
Bug: Issues with selecting the correct well when inputting 

### ISSUE THREAD

**Issue by ayeshasal** [klavinslab/aquarium-bugs#299]
## Bug report

- **Reproduce by:** Planning using a stripwell as an input (i.e., plan the "Run Gel" protocol)
- **Expected:** When you select which well you want to use, that is the well that should be saved and submitted 
- **Actual:** The first well of the first stripwell is always chosen. To illustrate: 
I click the second stripwell, selecting the fourth well. 
![image](https://user-images.githubusercontent.com/17604778/41128019-a6817976-6a61-11e8-9493-78111e24dcac.png)
After clicking save: 
![image](https://user-images.githubusercontent.com/17604778/41128038-c0f8156c-6a61-11e8-8dfd-251733591223.png)
The first stripwell, first well is selected. 

- **Acceptance criteria:** The stripwell/well combination I click on should be the one used in the plan.

**Comment by klavins** [comment]
Fixed this one. Thanks! I'll push the fix to production tonight.
