### ISSUE TITLE
Banner buttons hitboxes for links different than hitboxes for click events

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#3]
For example, if I click right below "Inventory" on the banner, I get the clicky fist and the shockwave animation, but I'm not linked to the Inventory page. I have to click the "Inventory" text to be linked to the page.
![inventory](https://user-images.githubusercontent.com/14169359/28089350-9c535696-663d-11e7-8bef-d48e4c4c7b0e.png)

**Comment by klavins** [comment]
fixed
