### ISSUE TITLE
Feature Request: it would be nice to be able to add inputs and operations to existing plans.

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#301]
## Feature request

User story: it would be nice to be able to add inputs and operations to existing plans. I'm not sure if this was the intended behavior, but I thought I could add additional operation and edit their inputs. In the screenshot below, you can see that I can add a Sequencing Module to an exising plan, but cannot set the primer input. Meanwhile, I _can_ connect the miniprep from another operation to the module.

**Comment by Gamemackerel** [comment]
I believe this issue is fixed on nursery, can you confirm and close?
Also I can't see your screenshot.
