### ISSUE TITLE
Greek letters removed when importing workflows

### ISSUE THREAD

**Issue by dvnstrcklnd** [klavinslab/aquarium-bugs#307]
## Bug report

The workflow importer silently removes greek letters from protocol code.

- **Reproduce by:** Importing the Standard Libs/Units library
- **Expected:** Greek letters, e.g., `µ`, are retained
- **Actual:** `MICROMOLAR = 'µM'` -> `MICROMOLAR = 'M'` upon import
- **Acceptance criteria:** Lines containing greek letters (or other special characters) are not altered.

**Comment by bjkeller** [comment]
Moved this to the aquarium repo: https://github.com/klavinslab/aquarium/issues/369#issue-522945744
