### ISSUE TITLE
Sequence URL

### ISSUE THREAD

**Issue by dvnstrcklnd** [klavinslab/aquarium-bugs#4]
In the Inventory -> new sample, it would be helpful if the field name were "Sequence URL" instead of just "Sequence"

**Comment by klavins** [comment]
That's actually something an admin user can change by editing the sample type information for Plasmid and changing the key for that field ("Sequence" in this case).

**Comment by klavins** [comment]
Be careful doing that too much though. Some operations get sample fields by name (although I don't think any get the Sequence field of a plasmid). Also, we tend only to edit sample type definitions after forming a consensus among lab managers and workflow developers that the edit is a good idea.
