### ISSUE TITLE
Manager sometimes miscounts waiting and pending operations

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#41]
We discovered this with Make Glycerol Stock, where inputs and preconditions were met, but the Manager interface still counted the pending MGSs as waiting. Selecting pending MGSs did, however, reveal the pending MGSs. Here's an example of the bug where some MGS operations are waiting and others are pending.
![mgs1](https://user-images.githubusercontent.com/14169359/28325910-0bfbd418-6b94-11e7-9f70-9beafcc2f948.png)
and after pending MGSs have been scheduled
![mgs2](https://user-images.githubusercontent.com/14169359/28325913-10cfe876-6b94-11e7-9d5e-9d7ec76cdbac.png)

**Comment by bjkeller** [comment]
Is this a protocol issue, or is it something in the `Protocol` class?

**Comment by cpc3** [comment]
This is becoming a bigger issue.  We have about 4-5 protocols that are doing this today and it's hard to keep track of/to click on every single protocol to see if something is "pending" even though it says there's none.

**Comment by bjkeller** [comment]
@klavins There seems to be an update issue for the `numbers` array when the manager view [operations table rows are created](https://github.com/klavinslab/aquarium/blob/master/app/views/operations/index.html.erb#L44).

When @gasnew updated the protocol preconditions to include the wait, the managers noticed that the counts in the table were not updated even though clicking on the table entries showed that the status of the operations had changed.

The current status is that the protocol preconditions have been rolled back.

**Comment by klavins** [comment]
A minrep I can run on my laptop would be very useful.

**Comment by bjkeller** [comment]
@gasnew can you provide @klavins with the preconditions and a scenario?

**Comment by gasnew** [comment]
I've made a fix for this that we should definitely merge before we update everything on Monday.

**Comment by klavins** [comment]
See my comment to your pull request. Still some work to do.

**Comment by klavins** [comment]
Garrett's fix for this was merged from pull request #264
