### ISSUE TITLE
It would be nice to have links to samples in Plan view

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#42]
The circled sample name, for example, would be a link to the sample in inventory.
![thing or something of thing for thhhh](https://user-images.githubusercontent.com/14169359/28332103-5a1c9650-6ba8-11e7-8aa3-dd99e5f6824a.png)

**Comment by klavins** [comment]
Done. And added a links to samples in the plan's operation's i/o.
