### ISSUE TITLE
Associate sequencing results with items (as well as with plans)

### ISSUE THREAD

**Issue by klavins** [klavinslab/aquarium-bugs#47]
I think it is essential to associate sequencing results for saved plasmid stocks along with a note of which part of the batched sequencing result is relevant. This way, people can find the sequencing results for plasmids without having to look up the plan they were obtained from.

**Comment by ayeshasal** [comment]
so i associated the results with the item--we'll need to change it when we include an input array of sequencing primers (so users know which result is associated with which primer), but users should be able to find the sequencing results for a specific item from the item itself.

**Comment by gasnew** [comment]
I reviewed this with David yesterday.

**Comment by gasnew** [comment]
I reviewed this with David yesterday.
