### ISSUE TITLE
No verification 'new item' for Plasmids 

### ISSUE THREAD

**Issue by wrightrc** [klavinslab/aquarium-bugs#54]
If I bring a new plasmid to aquarium that I have verified there is no way to create a verification certificate for the plasmid. The planner will always recognize this as 'unverified' and create sequencing tasks.

**Comment by gasnew** [comment]
If you input your plasmid to Aquarium as a Plasmid Stock (not Unverified Plasmid Stock), then the planner shouldn't prefer you to sequence it.

**Comment by wrightrc** [comment]
OK seems like this is just an issue related to the more specific 53. Closing.
