### ISSUE TITLE
Nice to make entire plan label expandable

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#56]
Really minor improvement, but its a little more work to click the Triangle on the left and move all the way to the right to do stuff with plans. It'd be nice to have the entire blue bar expand and contract the plan info so you can click on plans faster.
<img width="1059" alt="screen shot 2017-07-22 at 9 59 38 am" src="https://user-images.githubusercontent.com/10437900/28493170-a7436082-6ec6-11e7-8aed-8085a31e7f7b.png">

**Comment by klavins** [comment]
Done
