### ISSUE TITLE
It would be nice to have an interface for making collections

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#59]
This would be helpful for importing collections to the lab and for correcting for protocol errors.

**Comment by frba** [comment]
It would be great if we could change/edit the name of the columns and rows, to match with the names in plates. Like in the image below:

![Screenshot from 2019-03-27 12-04-37](https://user-images.githubusercontent.com/30867168/55092227-91004880-5088-11e9-82c8-84c38178f15a.png)

![Screenshot from 2019-03-27 12-04-37_2](https://user-images.githubusercontent.com/30867168/55092752-7e3a4380-5089-11e9-8de4-e9218c3de941.png)

**Comment by bjkeller** [comment]
Is this just for display purposes, or do you want to be able to use the information within a protocol?

**Comment by frba** [comment]
At first, I just thought about using it as a display. Because I was adding new samples to the database and I was confused to correlate well A1 with the 0,0 position and so on (A2 -> 0,1).
However, I believe having this information in the protocols would be useful.

**Comment by bjkeller** [comment]
OK, sorry I was confused.

Would it be sufficient for you to have these be plate coordinates? e.g., A01, B12...

**Comment by frba** [comment]
> Would it be sufficient for you to have these be plate coordinates? e.g., A01, B12...
>  **Yes, that is what I need.**
> In other words, is it correct that you don't need to have arbitrary row/column names? **No**

**Comment by bjkeller** [comment]
I'm going to close this issue, because technically it is done. But added corresponding issue on Aquarium repo (https://github.com/klavinslab/aquarium/issues/345) for @frba's request
