### ISSUE TITLE
Planner view

### ISSUE THREAD

**Issue by dvnstrcklnd** [klavinslab/aquarium-bugs#6]
In the planner view, can the samples be listed as "#{sample.id}: #{sample.name) in #{sample.container_type.name}"? This would help clarify how the sample is progressing through the transformations and changes state. Right now, seeing it listed exactly the same way makes it difficult to see what is happening.

**Comment by klavins** [comment]
Isn't the fourth column of the "Inputs, Outputs, and Parameters" box the container type? Or do you mean somewhere else?

**Comment by dvnstrcklnd** [comment]
I mean in the tree view of the workflow.

**Comment by klavins** [comment]
In that view, the container type is shown on the left when the sample input is selected. Since it is an input box, I didn't know where to put the container type while also keeping the tree small (they can get quite large). Ideas?

**Comment by dvnstrcklnd** [comment]
[image: Inline image 1]

**Comment by dvnstrcklnd** [comment]
<img width="494" alt="screen shot 2017-07-11 at 5 01 39 pm" src="https://user-images.githubusercontent.com/7586251/28096141-5feef4c6-665b-11e7-8f2e-e9681bf9f934.png">

**Comment by klavins** [comment]
ok.

**Comment by klavins** [comment]
![untitled](https://user-images.githubusercontent.com/4392589/28097964-561b7d90-6668-11e7-96a6-a0a2f516dca1.jpg)

How does this look?

**Comment by dvnstrcklnd** [comment]
Admittedly I was on an iPhone, but it took me a few minutes to notice what
you had done. Instead of right justifying the container, how about

9964: L1-AZI1-fdf&nbsp;<span style=color: blue>(Primer Aliquot)</span>

all left justified.

It's less of an issue in this workflow, but in the workflow Garrett and I
were working on today there were a lot of operations that had the same
input and output. It makes it hard to see what's happening to the sample.

**Comment by klavins** [comment]
The problem is that left justifying it gets in the way of the user's input. In your example "9964: L1-AZI1-fdf" is typed in by the user. I don't want them to have to type "9964: L1-AZI1-fdf (Primer Aliquot).

**Comment by dvnstrcklnd** [comment]
But that gets populated by autocomplete, right? I think I've done autocompletes that join two or more tables, but maybe too fussy for this. What you have is fine.
