### ISSUE TITLE
Itd be nice to have a convention for consumable inputs

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#60]
I was hoping to get some discussion on this concept of input item consumption.

Occasionally, there are inputs to protocols whose physical items will be completely consumed (i.e. deleted) by the end of the protocol. This can lead to situations in which two operations are launched that use the same input item that will be consumed by an operation. I think that there could be a useful 'mark as consumed' or 'to-be-consumed' option for inputs to protocols.

A simple example of this would be a media protocol that adds antibiotics to media to create a new item. Lets say a **500 mL bottle of LB** is changed to a **500 mL bottle of LB + Amp**. In this case, the original media is deleted or consumed by the protocol and a new item is produced. This could become an issue if two operations use the same bottle of base media. They both cannot fire and one of the operations must error out. If there was some convention for marking an input as 'to-be-consumed' or something, such that in the launcher, available items that are to be consumed by other operations should not even be options to select as inputs to other operations. The convention could also be useful in the sense that operations.store would also automatically mark any items that are consumed as deleted.

Does anyone have any thoughts on this?

**Comment by ayeshasal** [comment]
hey we just had this issue happen a couple times in the lab! i'm closing this issue though because cami just made a similar issue more recently, and labeled it critical -- which it is, because we've had to abort a couple of protocols/plans to get around it.
