### ISSUE TITLE
Cannot scroll in job steps view

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#65]
For example, this page cannot be fully seen without zooming out.
![scroll](https://user-images.githubusercontent.com/14169359/28692734-b46d67a8-72d6-11e7-978c-418d18ecd2d1.png)

Scrolling reveals more of the table of contents but does not reveal more of the current step.

**Comment by ayeshasal** [comment]
i'm closing this issue because justin made a duplicate and since that one's more recent, it's further up the list.
