### ISSUE TITLE
Unable to add images to protocols

### ISSUE THREAD

**Issue by dvnstrcklnd** [klavinslab/aquarium-bugs#67]
I can't seem to get any images to show up. I've tried .pdf, .png, and .jpg versions of the image. Tried switching to a directory name without spaces. I also tried adding the line

`image "Actions/NGS/remove_from_foil_package.jpg"`

to Klavins/Image Test. Still doesn't show up. Wonder if it is a permissions issue?

**Comment by dvnstrcklnd** [comment]
"Failed to load resource: the server responded with a status of 403 (Forbidden)"

**Comment by klavins** [comment]
Go to the S3 page for this image and click on "Make Public"

**Comment by dvnstrcklnd** [comment]
You mean this?

<img width="474" alt="screen shot 2017-08-01 at 7 03 43 am" src="https://user-images.githubusercontent.com/7586251/28822630-ff3d60e4-7687-11e7-8312-785244be353d.png">

Still doesn't work for me.

**Comment by dvnstrcklnd** [comment]
I get: 
"Error
An unexpected error occurred."

When I try to make it public.

**Comment by dvnstrcklnd** [comment]
Has this been resolved? I'm still not getting images to display.

**Comment by klavins** [comment]
Ok, I think there was a problem with AWS policies. I added a new policy that should make new images be public by default. I logged in as soslab and added an image, System/Test/kubb.jpg, and it seems to have made it public. Can you try adding a new image and seeing if it is public after you add it (no need to click "Make Public")?

**Comment by dvnstrcklnd** [comment]
That works, but it looks like the images is just totally public. I can open
it in an incognito using the URL. Is that what you want?

**Comment by klavins** [comment]
Yeah, I was thinking these would be public. Don't really see why not.
