### ISSUE TITLE
"Cost Undetermined" error for nonexistent operations (unable to launch plan)

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#68]
This error appears to occur in the following case:
- User builds plan with at least one unsatisfied operation input
- User removes that unsatisfied operation and **at least** the operation before it
- User satisfies the now dangling operation input (the one that used to be the output of the last removed operation) with at least one new operation.

For example:

![step1](https://user-images.githubusercontent.com/14169359/28727586-4476e862-737a-11e7-9eb2-d9139ce50b3e.png)

Plate -> Transform -> Assemble. The important part of this step is that no fragments are specified (this will later result in the error).

![step2](https://user-images.githubusercontent.com/14169359/28727695-9a84b0fe-737a-11e7-8ff0-833505ebaa31.png)

Plate -> Transform from Stripwell. Here we satisfy the "dangling operation input" (that from Plate) with Transform from Stripwell. After clicking "Launch," we are given the Cost Undetermined error.

I've experienced this a few times before, and I'm aware of two cases this week where users have struggled with it. The best workaround I've found is to make the plan again from scratch.

**Comment by gasnew** [comment]
We've encountered another bug that I think is related to this one. Essentially, in [this plan](http://52.27.43.242/launcher?plan_id=1326#), even if you remove Make Miniprep while replanning it, Make Miniprep and its predecessors will be submitted with the plan.

I think the 'x' button for removing operations while planning is somehow broken.

**Comment by klavins** [comment]
This should also be fixed by the new planner GUI. Hold tight.
