### ISSUE TITLE
Incorrect Operation ObjectType for output

### ISSUE THREAD

**Issue by gasnew** [klavinslab/aquarium-bugs#69]
See [plan 22407](http://52.27.43.242:81/launcher?plan_id=22407) as a minrep example. The goal operation takes Yeast Plates; the predecessor outputs Yeast Overnight for Antibiotic Plate or Yeast Plate. Even though the goal operation only takes plates, the predecessor supplies it with an overnight.

See the resulting jobs [51532](http://52.27.43.242:81/krill/log?job=51532) and [51534](http://52.27.43.242:81/krill/log?job=51534).

**Comment by klavins** [comment]
This should be fixed in the new planner GUI which will highlight transitions whose source i/o don't match object types.
