### ISSUE TITLE
Changes to planner front page

### ISSUE THREAD

**Issue by dyounger** [klavinslab/aquarium-bugs#70]
It is currently really difficult to track plans. I think it would probably be best to have a meeting with programmers and users to talk about this more in depth and come up with ideas, but here are a few of the basic issues:

- I have to hit "more" 4 times to get to plans that I scheduled at the beginning of this week. If I were interested in things that I did around the time of the 2.0, I would have to hit "more" 8 times. 
- The status options don't tell me much. "Done" is fine. "Waiting" means that either the protocol is chugging along as expected, something needs my attention, or there is an error in an early step of the plan. "Pending" means there is only one more step before the plan is done. "Error" means one of many things: I canceled the plan, a tech canceled the plan, Aquarium crashed, an item was missing, a step in the plan failed, etc. 
- All of the different types of plans are mixed in together depending on when I submitted them. This makes it very hard to see how things are going. I currently have 12 purify gel slice plans that will all be run together, but they are separated on the plan front page.

I was going to bring all of these issues up last  #week, but then I heard that there was a big update coming with the planner. So, I figured I would just wait and see what that brought. But, as the days go on and my list of plans grows, it is getting more and more difficult to manage.

**Comment by klavins** [comment]
Hopefully the new plans page with the folders addresses this. The one thing left to do is to highlight those plans requiring user input.
