### ISSUE TITLE
IWBNI the developer protocol tab autosaved

### ISSUE THREAD

**Issue by dvnstrcklnd** [klavinslab/aquarium-bugs#71]
Unfortunately this has become an ingrained expectation for me, especially using Mac and Google docs more.

**Comment by gasnew** [comment]
While I agree this would be nice, I think it's fairly complicated to do right in practice. For example, especially when I'm teaching someone or helping them debug, we'll both have the protocol code open in our browsers. Problems could arise if my version of the protocol were to keep saving over theirs as we're working together. I also semi-frequently have multiple versions of a single protocol open in different tabs if I'm doing a major refactor. I think protocols saving my progress out of my control without other measures to ensure synchronized protocol versions can be dangerous.

What would you think about a "Do you want to save recent changes?" dialog box if you try to navigate away from a protocol you're working on? That should prevent loss of progress, and it would be more transparent to the user. klavinslab/aquarium#183

**Comment by dvnstrcklnd** [comment]
I agree with everything you say here, Garrett.

**Comment by dvnstrcklnd** [comment]
I think maybe this could be done in a fairly risk-free way it it only saved recovery files to the filesystem instead of trying to save to the SQL database.

**Comment by bjkeller** [comment]
Also ref #192

**Comment by bjkeller** [comment]
I made an umbrella issue for editor issues linked to this issue: #193, and am marking this as closed.
