### ISSUE TITLE
Discard Item - Yeast Glycerol Stock

### ISSUE THREAD

**Issue by wmvoje** [klavinslab/aquarium-bugs#78]
When I attempt a "discard item" plan for the glycerol stock associated with yeast strain "19834: pMOD6-pGRR-W8-yeGFP, pMOD4G-dcas9-mxi1, pMOD8A-RGR-W10, pMOD8-pGALz4_GR-W8, pMODKan-HO-pACT1-ZEV4"

I get the error "Cost Undetermined: Discard Item operation: Child sample not specified for input 'Item'." 

As far as I can tell there is no Child Sample to reference for this operation. I think this is a bug.

**Comment by ayeshasal** [comment]
it should be working now. thanks for the bug report!
