### ISSUE TITLE
Upload spreadsheet doesn't ignore Byte Order Mark

### ISSUE THREAD

**Issue by jvrana** [klavinslab/aquarium-bugs#82]
I frequently get this error:
` "Error processing spreadsheet: Could not find sample type ï»¿SampleTypeName"`

 This mark **ï»¿** is a byte order mark (I guess) that I think the upload spreadsheets should ignore. Its present when I save a csv through excel or through any of my text editors. Its pretty annoying on my end to remove it.

For ruby, I believe you add the "r:bom|utf-8" tag to fix this?

```
File.open('file.txt', "r:bom|utf-8"){|file|
  ...
}
```

**Comment by klavins** [comment]
Can you send me a csv file that causes this problem so I can test it?

**Comment by jvrana** [comment]
Hmmmm, ok I sent it via slack, however in the process of sending it, the error disappeared after I redownloaded it from slack and tried to upload it.

**Comment by klavins** [comment]
Gotta love those one line fixes. In this case, it was reading the file as text in javascript instead of as a binary string. Seems to work on your test files and other test files that I've bene using.
