### ISSUE TITLE
Editing containers

### ISSUE THREAD

**Issue by dvnstrcklnd** [klavinslab/aquarium-bugs#90]
For some reason I can't edit the name of http://52.27.43.242:81/object_types/666 but I can edit the name of http://52.27.43.242:81/object_types/667

It hasn't escaped my attention that this particular container bears the mark of the beast, but alas, Eddie is having the same problem.

When I try to save the changes it just dumps me to a blank screen.

**Comment by klavins** [comment]
This was due to the name already being taken, but the backend redirecting to the wrong view upon getting an activerecord.save error. I've fixed it now and you should see an error message at the top of the object type edit page.
