### ISSUE TITLE
Editing plans after using "auto"

### ISSUE THREAD

**Issue by dyounger** [klavinslab/aquarium-bugs#92]
If a plan is made using "auto" and then you want to go back and change some of it (ex. the first half of a plan is auto generated correctly, but want to change some things) the plan fails. You get a "cost undetermined: x operation: child sample not specified for input 'y'. Even if all of the items are specified.

**Comment by klavins** [comment]
Will be resolved by using templates in the planner.

**Comment by ayeshasal** [comment]
the auto button is no more
