### ISSUE TITLE
Manually make a "plasmid stock" from an "unverified plasmid stock"

### ISSUE THREAD

**Issue by dyounger** [klavinslab/aquarium-bugs#97]
If I get sequencing results back or verify a plasmid another way, I would like to change the status of a plasmid stock from unverified to verified.

**Comment by klavins** [comment]
This would mean the user needs to change the object type of an item manually from the inventory (or the planner). Or maybe in the item popup.

**Comment by gasnew** [comment]
This is solved in the new pending Cloning workflow, where there are no restrictions imposed on Unverified Plasmid Stocks, and Unverified Plasmid Stocks are no longer produced.
